-- =====================================================================
-- ENCURTADOR HX (lnk_*) — runbook
-- Criado em 03/09/2026. Substitui o esquema splitter_* (que estava vazio
-- desde 08/2026 e tinha policies anon_read USING true).
--
-- Este arquivo NÃO é executável de ponta a ponta: é o mapa de quem faz o
-- quê, mais as armadilhas que já custaram tempo. As migrations reais estão
-- aplicadas no Supabase ntavetjmfotlwmcgwsju (lnk_01 a lnk_34). Da lnk_27 em
-- diante o SQL completo esta versionado em backend/migrations/.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ONDE CADA COISA RODA
-- ---------------------------------------------------------------------
-- Painel .......... este repo, aba Links (src/views/Links.tsx)
-- Redirector ...... Cloudflare Worker "hx-links", repo PRIVADO hx-links
--                   no ar em https://l.hx-corp.com/<slug>
-- Fonte de verdade  Postgres (tabelas lnk_*)
-- Cache de leitura  Workers KV, namespace hx-links-cache
--                   4529e1b8422148a99b660693c54c2bbe, chave l:<host>:<slug>
--
-- O painel NUNCA fala com a Cloudflare. Ele grava no Postgres, um trigger
-- enfileira em lnk_kv_fila, e o cron lnk_kv_worker_10s publica no KV.
-- Motivo: o papel authenticated tem statement_timeout de 8s e RPC de painel
-- que faz HTTP trava a tela ([[rpc_painel_nunca_faz_http]]).

-- ---------------------------------------------------------------------
-- CRONS
-- ---------------------------------------------------------------------
-- lnk_kv_worker_10s       10 seconds   publica links editados no KV
-- lnk_dominio_worker_1min 1 min        provisiona domínio novo na Cloudflare
-- lnk_rollup_5min         5 min        agrega lnk_cliques -> lnk_cliques_dia
--
-- pg_cron aceita intervalo em segundos neste projeto (evo_worker_10s já roda
-- assim desde 08/2026). Por isso a propagação de uma edição fica em ~10s em
-- vez do minuto do cron clássico.

-- ---------------------------------------------------------------------
-- SEGURANÇA
-- ---------------------------------------------------------------------
-- Todas as lnk_* têm RLS ligada e ZERO policy: fechado por padrão.
-- O painel não lê nada direto; tudo passa por RPC security definer com gate
-- mod_is_operador(). Este repo é PÚBLICO e publica o nome da RPC, então
-- esconder botão no front não é permissão.
--
-- O Worker NÃO usa service_role nem JWT de serviço. Ele manda um token
-- próprio (secret EDGE_TOKEN), comparado pelo SHA-256 em lnk_edge_tokens;
-- o token cru vive só no Worker e no Vault (lnk_edge_token_worker).
-- Se o Worker vazar, o escopo do estrago é: resolver um link e gravar um
-- clique. Nada mais.
--
-- Conferir a qualquer momento (tem que dar false em todas):
--   select relname, has_table_privilege('anon','public.'||relname,'SELECT')
--   from pg_class where relname like 'lnk\_%' and relkind='r';
--
-- Atenção ao LIKE: 'lnk[_]%' NÃO escapa o underscore no Postgres (colchete não
-- é metacaractere aqui) e devolve zero linha em silêncio. O escape é 'lnk\_%'.

-- ---------------------------------------------------------------------
-- COMO TESTAR AS FUNÇÕES COM GATE
-- ---------------------------------------------------------------------
-- Função com gate esconde o próprio erro: rodando como superusuário o
-- caminho do operador nem chega a executar. Foi assim que o bug do trigger
-- (new.link_id numa tabela sem essa coluna) só apareceu no teste com role.
--
--   begin;
--   set local role authenticated;
--   set local request.jwt.claims = '{"email":"matheus@hookmidia.com"}';
--   select public.lnk_painel_dominios();
--   rollback;
--
-- Atenção: dentro desse bloco você TAMBÉM não consegue dar select nas
-- tabelas lnk_* (é o comportamento correto). Pegue os ids do retorno da RPC.

-- ---------------------------------------------------------------------
-- ARMADILHAS QUE JÁ CUSTARAM TEMPO
-- ---------------------------------------------------------------------
-- 1. RAIZ REGISTRÁVEL, NÃO HOSTNAME.
--    Blocklist (Google Safe Browsing, Spamhaus DBL) opera no domínio
--    registrável: uma listagem em exemplo.com pega todos os subdomínios.
--    Seis subdomínios da mesma raiz são UM alvo, não seis. Por isso
--    lnk_dominios.raiz_registravel existe e o rodízio nunca sorteia dois
--    hostnames da mesma raiz na mesma rodada.
--    Corolário: l.hx-corp.com nasce com no_rodizio = false, porque a raiz
--    hx-corp.com carrega o MX do e-mail da empresa, o n8n, o Metabase e o
--    Evolution. Ele serve para link avulso, não para disparo em massa.
--
-- 2. CONTADOR NUNCA NA LINHA QUE O REDIRECT LÊ.
--    O escopo original deste projeto propunha
--      UPDATE redirects SET cliques = cliques+1 WHERE slug=$1 RETURNING url
--    Isso serializa todos os cliques do mesmo link na mesma linha (hot row),
--    enche a tabela de versões mortas e, pior, acopla venda a contador: se a
--    escrita falha, o usuário não recebe redirect. Aqui o clique é
--    append-only em lnk_cliques e o contador é derivado (lnk_cliques_dia).
--    Errei nisso uma vez durante a construção: pus um UPDATE de contador
--    dentro do lnk_edge_resolver e o Postgres recusou (função stable).
--
-- 3. NADA DE I/O ANTES DO 302.
--    Lei da casa desde 09/08/2026, quando inverter a ordem cortou o redirect
--    de 530ms para 449ms. No Worker: isolate -> KV -> Postgres, e o clique
--    só em ctx.waitUntil().
--
-- 4. VIÉS DE CONSTRUÇÃO EM por_destino.
--    Comparar o peso de AGORA com cliques que aconteceram sob o peso ANTIGO
--    faz o painel acusar desvio que não existe. A janela de comparação começa
--    em greatest(v_desde, lnk_destinos.updated_at), e a linha carrega
--    peso_mudou_no_periodo + comparavel para a tela não cobrar aderência de
--    um número que mudou de regra no meio.
--
-- 5. EXPOSIÇÃO SE MEDE EM MENSAGEM, NÃO EM CLIQUE.
--    lnk_atribuicoes existe para isso. Medir exposição por clique tem viés de
--    sobrevivência: domínio já bloqueado não gera clique, então pareceria
--    "pouco exposto" justamente quando está morto.
--
-- 6. ROBÔ NÃO É CLIQUE.
--    O crawler do WhatsApp busca a URL enquanto a pessoa ainda está digitando,
--    antes de a mensagem ser enviada. A classificação é dado versionado
--    (classificador_v) e reprocessável; a original nunca é sobrescrita em
--    silêncio. Calibrado contra os 34 user agents reais de sortudao_wa_cliques
--    (hx-links/scripts/testa-uas-reais.mjs, 35/35 corretos).
--
-- 7. SLUG DIFERENTE POR DOMÍNIO.
--    Se dominio-a.com/x7k2 e dominio-b.com/x7k2 existissem, o caminho idêntico
--    ligaria um domínio no outro. Por isso lnk_urls guarda um slug por
--    (link, domínio), gerado aleatoriamente sem caracteres ambíguos.

-- ---------------------------------------------------------------------
-- V2 (15/09/2026) — o que a aba Links usa alem do rodizio
-- PRD: hookmidia-claude-config/contexto/GESTOR_GRUPOS_HX/PRD_links_v2_2026-09-15.md
-- ---------------------------------------------------------------------
-- Leitura (gate mod_is_operador):
--   lnk_painel_listar(busca, projeto, limite, ordem, tag, estado)
--       ordem: recentes | cliques | nome | ultimo. Devolve url_curta,
--       sparkline_7d (7 ints), tags, estado (ativo/pausado/congelado/
--       expirado), cliques_hoje/7d/total, pessoas_7d (NULL sem cookie),
--       protegido. Busca acha por nome, slug, destino e tag.
--   lnk_painel_link(link_id, de, ate, grao)
--       detalhe: kpis (cliques/robos/bloqueados/pessoas/ips/completude),
--       serie por hora (ate 2 dias) ou dia, por_aparelho/sistema/navegador/
--       familia/pais/regiao/cidade/referer/utm, por_destino (peso real x
--       configurado com janela truncada), ultimos_acessos, historico e
--       o bloco `notas` com a camada didatica de cada metrica.
--   lnk_painel_tags(projeto)
--
-- Escrita (gate mod_is_operador; tudo valida ANTES de gravar e devolve
-- {ok:false, erro} em portugues; nada fica meio-escrito):
--   lnk_criar(..., p_slug, p_dominio, p_tags, p_observacao, p_expira_em, p_preview)
--       os 6 primeiros parametros sao os de sempre; slug custom vai pro
--       dominio institucional (fora do rodizio) se p_dominio for null.
--   lnk_link_editar(link_id, patch)   so o que veio no patch muda.
--       destinos = lista completa (quem sai e DESLIGADO, nunca apagado:
--       lnk_cliques.destino_id aponta pra ele). params = lista completa.
--       Nunca toca em lnk_urls.
--   lnk_link_estado(link_id, 'ativo'|'pausado'|'congelado', forcar)
--       pausado = fora do ar (destino_expirado do link ou 404 do dominio).
--       Link com URL protegida pede forcar.
--   lnk_url_custom(link_id, hostname, slug, forcar)
--       cria ou renomeia o slug do link naquele dominio. Renomear com
--       clique/entrega pede forcar; URL protegida NUNCA renomeia.
--       Reservados: api admin app login logout static assets www health
--       status dev test null undefined robots favicon sitemap warm.
--
-- Historico: lnk_link_historico (append-only; acao criado/editado/estado/
-- slug, campos, antes/depois, por_email). RLS ligada, zero policy.
--
-- URL protegida: lnk_urls.protegida = slug em producao fora do nosso
-- controle. eq8egq (pop-up do PDM) nasce protegida; so o banco desprotege.
--
-- UA: lnk_parse_ua(text) preenche ua_familia/device/os/browser com as
-- MESMAS regras do Worker (parseUA em hx-links/src/index.js). Versao das
-- regras = lnk_ua_v() aqui e UA_V la. Mudou regra: sobe os dois e roda
--   select lnk_reclassificar_ua(lnk_ua_v());
-- lnk_edge_clique parseia no insert quando o Worker nao mandou aparelho,
-- entao a tela nao depende do deploy do Worker pra ter device preenchido.
-- Paridade conferida por hx-links/scripts/testa-ua.mjs (fixture de 27 UAs).
--
-- Cookie hxv (Worker >= 1.2.0): "pessoas" honestas e A/B por pessoa
-- estavel. Colunas hxv, hxv_novo em lnk_cliques. Antes do 1.2.0 a caixa
-- "pessoas" vem NULL, nao zero.
--
-- KV: link fora do ar vira tipo 'purge' em lnk_kv_fila (DELETE na chave);
-- slug renomeado purga a chave antiga. Propagacao ate 90 s (isolate 30 s +
-- KV cacheTtl 60 s).
--
-- Vigia: lnk_vigia_404() a cada 30 min (cron lnk_vigia_404_30min):
-- slug inexistente com >= 20 acessos de GENTE (celular/tablet ou
-- navegacao_real) em 2h -> WhatsApp do Matheus via notificar_whatsapp
-- ('links', cooldown 6h por slug). lnk_vigia_404(true) = dry-run.
--
-- Slugs legados recriados em 15/09/2026 como links proprios (tags legado,
-- pdm): grupo-vip-pix-do-milhao e comunidade-vip-diego -> sndflw.com/i/
-- comunidades-03. Antes disso, 9.202 cliques de compradores cairam na home.
--
-- 8. SMOKE TEST COM UA DE GENTE VIRA CLIQUE.
--    curl com user-agent de Instagram + Sec-Fetch de navegacao e
--    classificado como humano e entra em "cliques". Pra smoke, usar o
--    curl cru (UA curl/x vira bot) ou marcar as linhas como 'interno'
--    depois (foi o que aconteceu em 15/09: 4 linhas smoke_f1_15_09).

-- ---------------------------------------------------------------------
-- CADASTRAR UM DOMÍNIO NOVO (o que o Matheus precisa fazer)
-- ---------------------------------------------------------------------
-- 1. Ter o domínio e apontar os nameservers para a nossa conta Cloudflare.
-- 2. Painel: aba Links > Domínios > cadastrar.
-- 3. O resto é automático: lnk_dominio_worker cria o Custom Domain do Worker,
--    a Cloudflare cria o registro de DNS e emite o certificado, e o domínio
--    vira 'ativo'. Todos os links do projeto ganham uma URL nele na hora.
--
-- Se ficar preso em 'pendente' com "a zona ainda não está na nossa conta",
-- é porque o passo 1 não foi concluído.

-- ---------------------------------------------------------------------
-- F3 (15/09/2026, lnk_33 + lnk_33b + lnk_34): projetos, lote e API com chave
-- ---------------------------------------------------------------------
-- Direcao do Matheus: a aba Links serve TODOS os projetos da HX. O projeto
-- e um rotulo que separa a lista; o dominio institucional (projeto_id null)
-- serve a todos, e dominio novo nasce global.
--
-- Projetos (gate mod_is_operador):
--   lnk_projetos_listar()            -> [{slug, nome, links, links_no_ar, ...}]
--   lnk_projeto_criar(nome, slug?)   -> slug derivado do nome quando nao vem
--   lnk_link_editar(id, {projeto})   -> move o link; ganha URL nos dominios
--                                       daquele projeto, as antigas seguem valendo
--
-- Lote (gate lnk_pode):
--   lnk_criar_lote(projeto, linhas [{n, url, nome?, slug?, tags?}], dry, defaults)
--       ate 500 linhas; dry=true so valida e devolve linha a linha
--       {ok, erro}; dry=false cria cada linha valida em SUBTRANSACAO (uma
--       ruim nao derruba as outras) e devolve id + url_curta. A tela manda
--       50 por chamada ao criar (statement_timeout de 8 s do authenticated).
--
-- API publica (anon key + chave hxl_ no corpo; nunca service_role):
--   lnk_api_criar(token, link jsonb)       escopo api:criar
--   lnk_api_ler(token, link_id?, url?)     escopo api:ler   (snapshot + kpis)
--   lnk_api_listar(token, projeto?, ...)   escopo api:ler
--   lnk_api_editar(token, link_id, patch)  escopo api:editar (patch da tela +
--                                          estado: ativo|pausado|congelado)
--   Toda resposta e {ok, ...}; token invalido/revogado/sem escopo devolve
--   {ok:false, erro:'nao_autorizado'}; excecao vira {ok:false, erro}.
--   Regras do gate (lnk_34): a chave tem ESCOPO DE PROJETO (lnk_edge_tokens.
--   projetos; null = todos, so uso interno) - link fora do escopo responde
--   link_nao_encontrado, projeto fora do escopo nao_autorizado; link com URL
--   PROTEGIDA (colada em producao, ex. eq8egq) nunca e editavel pela API
--   (link_protegido); lnk_api_editar e tudo-ou-nada (erro em qualquer parte
--   = RAISE + rollback, JSON volta pelo DETAIL).
--   Como funciona por dentro: lnk_api_auth valida (sha256 + escopo) e conta
--   o uso; a funcao seta lnk.api='1' e lnk.ator='api:<nome>' com set_config
--   LOCAL a transacao e chama a RPC do painel, cujo gate agora e lnk_pode()
--   = mod_is_operador() OU lnk.api='1'. O historico grava o ator da API.
--
-- Chaves (gate mod_is_operador; tela Links > API):
--   lnk_token_criar(nome, escopos[], projetos[] | null)
--                                     -> devolve a chave UMA vez (hxl_ + 48 hex);
--                                        o banco guarda sha256 + prefixo; o nome
--                                        fica reservado mesmo depois de revogada
--   lnk_tokens_listar()               -> so chaves api:*; a do Worker nao aparece
--   lnk_token_revogar(id)             -> imediato; recusa a chave do Worker
--
-- Armadilha 9: papel anon tem statement_timeout de 3 s. A API cria UM link
-- por chamada; pra muitos, a tela (lote) ou chamadas em sequencia.
-- Medido 15/09: lote real de 50 linhas = 423 ms (authenticated, 8 s de teto).

-- ---------------------------------------------------------------------
-- DEPLOY DO WORKER
-- ---------------------------------------------------------------------
-- select public.lnk_deploy_worker($js$ ...conteúdo de hx-links/src/index.js... $js$);
--
-- Feito a partir do Postgres de propósito: o token da conta Cloudflare e os
-- secrets do Worker são montados lá dentro, lidos do Vault, e nunca passam
-- pelo terminal. A função devolve o SHA-256 do que subiu; comparar com
-- `sha256sum src/index.js` no repo prova que o que está no ar é o que está
-- versionado.

-- ---------------------------------------------------------------------
-- SMOKE TEST
-- ---------------------------------------------------------------------
-- curl -sI -H 'accept-language: pt-BR' -H 'sec-fetch-dest: document' \
--      -H 'sec-fetch-mode: navigate' https://l.hx-corp.com/teste01
--   espera: 302 + header x-hx + Location com as UTMs e o hxcid
--
-- Latência medida em 03/09/2026 (Desktop, Porto Alegre, 10 amostras):
--   TTFB médio 110ms, contra 437-478ms do redirect do n8n em NYC1.
--   Dentro do Worker: 0ms com cache de isolate, 3,5ms via KV.
--   O que sobra é rede e TLS até a borda, não código nosso.
